database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "Roottoor1..?"
  dbname: "test_db"
email:
  host: "smtp.example.com"
  port: 587
  username: "your-email@example.com"
  password: "your-email-password"
  from: "your-email@example.com"
  to: "recipient@example.com"