name: Systemd Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o system-metrics cmd/systemmetrics/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          system-metrics
          !**/excluded-directory/**
          !**/excluded-file.txt