name: Systemd Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -o system-metrics cmd/systemmetrics/main.go

      - name: Ensure public directory exists
        run: mkdir -p ./public

      - name: Copy files to public directory
        run: cp -r path/to/source/files/* ./public/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: systemmetrics
          path: ./public
          retention-days: 1
